"""empty message

Revision ID: 645f08e9ee32
Revises: 
Create Date: 2022-08-12 23:21:26.216421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645f08e9ee32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
